-- 1.⁠ ⁠WAQTD ENAME MANAGER'S NAME AND EMPLOYEE'S LOCATION FOR THE EMPLOYEES WORKING AS 'CLERK'

-- 2.WAQTD ENAME, MANAGER'S SALARY AND MANAGER'S LOCATION IF MANAGER WORKS AS PRESIDENT'

-- 3.⁠ ⁠WAQTD ENAME, EMPLOYEE'S SALARY, MANAGER'S NAME MANAGER'S SALARY ALONG WITH EMPLOYEES DNAME IF EMPLOYEE EARNS MORE THAN MANAGER.

-- 4.⁠ ⁠WAQTD ENAME, SAL MANAGER'S NAME MANAGER'S DNAME IF MANAGER WORKS IN NEW YORK WITH SALARY MORE THAN 3000.

-- 5.⁠ ⁠WAQTD ENAME, EMPLOYEE'S DNAME, MANAGER'S NAME MANAGER'S DNAME IF EMP AND MANAGER WORKS IN SAME LOC

-- 6.⁠ ⁠WAQTD ENAME, EMPLOYEES' HIREDATE, MANAGER'S HIREDATE IF MANAGER WAS HIRED BEFORE THE EMPLOYEE IN TO ACCOUNTING DEPARTMENT

-- 7.WAQTD EMPLOYEE'S NAME, MANAGER'S NAME ALONG WITH, MANAGER'S MANAGER'S NAME

-- 8.⁠ ⁠WAQTD ENAME, DNAME, MANAGER'S NAME HIS DEPT NAME IF MANAGER IS HIRED BEFORE 1982

-- 9.WAQTD EMPLOYEE'S NAME WITH DNAME, MANAGER'S NAME WITH LOC ALONG WITH, MANAGER'S MANAGER'S NAME WITH LOC

-- 10.WAQTD EMPLOYEE'S NAME WITH DNAME, MANAGER'S SAL WITH DNAME ALONG WITH, MANAGER'S MANAGER'S JOB WITH DNAME 
--    IF EMPLOYEE WORKS IN DEPT 10, MANAGER WORKS AS PRESIDENT OR ACTUAL MANAGER AND MANAGER'S MANAGER SALARY MUST BE GREATER OR EQUAL TO MANAGER'S SALARY

use scott;

-- 1.⁠ ⁠WAQTD ENAME MANAGER'S NAME AND EMPLOYEE'S LOCATION FOR THE EMPLOYEES WORKING AS 'CLERK'
SELECT E1.ENAME, D1.LOC,E2.ENAME
FROM EMP E1,EMP E2,DEPT D1
WHERE E1.JOB = 'CLERK' AND E1.MGR = E2.EMPNO AND E1.DEPTNO = D1.DEPTNO;

-- 2.WAQTD ENAME, MANAGER'S SALARY AND MANAGER'S LOCATION IF MANAGER WORKS AS PRESIDENT'
SELECT E1.ENAME, E2.SAL,D2.LOC
FROM EMP E1,EMP E2,DEPT D2
WHERE E1.MGR = E2.EMPNO AND E2.DEPTNO = D2.DEPTNO AND E2.JOB = 'PRESIDENT';

-- 3.⁠ ⁠WAQTD ENAME, EMPLOYEE'S SALARY, MANAGER'S NAME MANAGER'S SALARY ALONG WITH EMPLOYEES DNAME IF EMPLOYEE EARNS MORE THAN MANAGER.
SELECT E1.ENAME,E1.SAL,D1.DNAME,E2.ENAME,E2.SAL
FROM EMP E1,EMP E2,DEPT D1
WHERE E1.MGR = E2.EMPNO AND E1.DEPTNO = D1.DEPTNO AND E1.SAL > E2.SAL;

-- 4.⁠ ⁠WAQTD ENAME, SAL MANAGER'S NAME MANAGER'S DNAME IF MANAGER WORKS IN NEW YORK WITH SALARY MORE THAN 3000.
SELECT E1.ENAME,E1.SAL,E1.ENAME,D2.DNAME
FROM EMP E1, EMP E2,DEPT D2
WHERE E1.MGR = E2.EMPNO AND E2.DEPTNO = D2.DEPTNO AND D2.LOC = 'NEW YORK' AND E2.SAL > 3000;

-- 5.⁠ ⁠WAQTD ENAME, EMPLOYEE'S DNAME, MANAGER'S NAME MANAGER'S DNAME IF EMP AND MANAGER WORKS IN SAME LOC
SELECT E1.ENAME,D2.DNAME,E2.ENAME,D2.DNAME
FROM EMP E1,EMP E2,DEPT D1,DEPT D2
WHERE E1.MGR = E2.EMPNO AND E1.DEPTNO = D1.DEPTNO AND E2.DEPTNO = D2.DEPTNO AND D1.LOC = D2.LOC;

-- 6.⁠ ⁠WAQTD ENAME, EMPLOYEES' HIREDATE, MANAGER'S HIREDATE IF MANAGER WAS HIRED BEFORE THE EMPLOYEE IN TO ACCOUNTING DEPARTMENT
SELECT E1.ENAME,E1.HIREDATE,E2.HIREDATE
FROM EMP E1,EMP E2,DEPT D1,DEPT D2
WHERE E1.MGR = E2.EMPNO AND E2.HIREDATE < E1.HIREDATE AND D1.DNAME = 'ACCOUNTING' AND D2.DNAME = 'ACCOUNTING';

-- 7.WAQTD EMPLOYEE'S NAME, MANAGER'S NAME ALONG WITH, MANAGER'S MANAGER'S NAME
SELECT E1.ENAME,E2.ENAME,E3.ENAME
FROM EMP E1,EMP E2, EMP E3
WHERE E1.MGR = E2.EMPNO AND E2.MGR = E3.EMPNO;

-- 8.⁠ ⁠WAQTD ENAME, DNAME, MANAGER'S NAME HIS DEPT NAME IF MANAGER IS HIRED BEFORE 1982
SELECT E1.ENAME,D1.DNAME,E2.ENAME,D2.DNAME
FROM EMP E1,EMP E2,DEPT D1,DEPT D2
WHERE E1.MGR = E2.EMPNO AND E1.DEPTNO = D1.DEPTNO AND E2.DEPTNO = D2.DEPTNO AND E2.HIREDATE < '1982-01-01';

-- 9.WAQTD EMPLOYEE'S NAME WITH DNAME, MANAGER'S NAME WITH LOC ALONG WITH, MANAGER'S MANAGER'S NAME WITH LOC
SELECT E1.ENAME,D1.DNAME,E2.ENAME,D2.LOC,E3.ENAME,D3.LOC
FROM EMP E1,EMP E2,EMP E3, DEPT D1,DEPT D2,DEPT D3
WHERE E1.MGR = E2.EMPNO AND E2.MGR = E3.EMPNO AND E1.DEPTNO = D1.DEPTNO AND E2.DEPTNO = D2.DEPTNO AND E3.DEPTNO = D3.DEPTNO;

-- 10.WAQTD EMPLOYEE'S NAME WITH DNAME, MANAGER'S SAL WITH DNAME ALONG WITH, MANAGER'S MANAGER'S JOB WITH DNAME 
--    IF EMPLOYEE WORKS IN DEPT 10, MANAGER WORKS AS PRESIDENT OR ACTUAL MANAGER AND MANAGER'S MANAGER SALARY MUST BE GREATER OR EQUAL TO MANAGER'S SALARY
SELECT E1.ENAME,D1.DNAME,E2.SAL,D2.DNAME,E3.JOB,D3.DNAME
FROM EMP E1,EMP E2,EMP E3,DEPT D1,DEPT D2,DEPT D3
WHERE E1.MGR = E2.EMPNO AND E2.MGR = E3.EMPNO AND E1.DEPTNO = D1.DEPTNO AND E2.DEPTNO = D2.DEPTNO AND E3.DEPTNO = D3.DEPTNO AND E1.DEPTNO = 10 AND
E2.JOB IN('PRESIDENT','MANAGER') AND E3.SAL >= E2.SAL;
