USE SCOTT;

-- 1.⁠ ⁠LIST ENAME, JOB, ANNUAL SAL, DEPTNO, DNAME WHO EARN 30000 PER YEAR AND WHO ARE NOT CLERKS
	SELECT EMP.ENAME,EMP.JOB,EMP.SAL*12,EMP.DEPTNO,DEPT.DNAME
    FROM EMP,DEPT
    WHERE EMP.DEPTNO = DEPT.DEPTNO AND EMP.SAL*12 = 30000 AND EMP.JOB != 'CLERK';

--  2.⁠ ⁠LIST OUT THE ALL EMPLOYEES BY NAME AND EMPLOYEE NUMBER ALONG WITH THEIR MANAGER'S NAME AND EMPLOYEE NUMBER
	SELECT E1.ENAME,E1.EMPNO,E2.ENAME,E2.EMPNO
    FROM EMP E1,EMP E2
    WHERE E1.MGR = E2.EMPNO;

-- 3.DISPLAY ENAME, DNAME EVEN IF THERE NO EMPLOYEES WORKING IN A PARTICULAR DEPARTMENT. -----------(*)
	SELECT EMP.ENAME,DEPT.DNAME
    FROM EMP LEFT JOIN DEPT
    ON EMP.DEPTNO = DEPT.DEPTNO
    UNION
    SELECT EMP.ENAME,DEPT.DNAME
    FROM EMP RIGHT JOIN DEPT
    ON EMP.DEPTNO = DEPT.DEPTNO;
    
--  4.⁠ ⁠DISPLAY THE DEPARTMENT NAME ALONG WITH TOTAL SALARY IN EACH DEPARTMENT
	SELECT DEPT.DNAME,SUM(SAL)
    FROM DEPT LEFT JOIN EMP
    ON DEPT.DEPTNO = EMP.DEPTNO
    GROUP BY DNAME
    
    UNION
    
    SELECT DEPT.DNAME, SUM(SAL)
    FROM DEPT RIGHT JOIN EMP
    ON DEPT.DEPTNO = EMP.DEPTNO
    GROUP BY DNAME;
    

-- 5.DISPLAY EMPLOYEE NAME AND DEPARTMENT NAME FOR EACH EMPLOYEE
	SELECT ENAME,DNAME
    FROM EMP LEFT JOIN DEPT
   ON EMP.DEPTNO = DEPT.DEPTNO ;
   
  --  UNION
--    SELECT ENAME,DNAME
--     FROM EMP RIGHT JOIN DEPT
--    ON EMP.DEPTNO = DEPT.DEPTNO ;
   
   

-- 6.DISPLAY LOCATION NAME OF THE EMPLOYEE WHO EARN COMMISSION.
	SELECT LOC 
    FROM DEPT
    WHERE DEPTNO IN (SELECT DEPTNO
						FROM EMP
                        WHERE COMM IS NOT NULL);
	
    SELECT DISTINCT LOC 
    FROM EMP,DEPT
    WHERE EMP.DEPTNO = DEPT.DEPTNO AND COMM IS NOT NULL;

-- 7.DISPLAY DEPT NAME OF THE EMPLOYEE WHO EARN MIN SALARY AND HAVE NO REPORTING MANAGER.
	SELECT DNAME
    FROM DEPT
    WHERE DEPTNO IN (SELECT DEPTNO
						FROM EMP
                        WHERE SAL IN (SELECT MIN(SAL)
										FROM EMP) AND MGR IS NULL);
    
SELECT DNAME
FROM DEPT,EMP
WHERE DEPT.DEPTNO = EMP.DEPTNO AND SAL IN (SELECT MIN(SAL) FROM EMP) AND MGR IS NULL;
-- 8 . DISPLAY DEPT NAME, LOC OF ALL THE EMPLOYEES WHO ARE REPORTING TO SMITH.
	SELECT DNAME,LOC 
    FROM DEPT
    WHERE DEPTNO IN (SELECT DEPTNO
						FROM EMP
                        WHERE MGR IN (SELECT EMPNO
										FROM EMP
                                        WHERE ENAME = 'SMITH'));
	
    -- BY USING JOIN
    SELECT D1.DNAME,D1.LOC
    FROM EMP E1,EMP E2, DEPT D1
    WHERE E1.MGR = E2.EMPNO AND E1.DEPTNO = D1.DEPTNO AND E2.ENAME = 'SMITH';
    
-- 9.LIST ALL THE DEPT NAME AND LOCATION OF ALL THE SALESMAN MANAGER'S MANAGER.
	SELECT DNAME, LOC
    FROM DEPT
    WHERE DEPTNO IN (SELECT DEPTNO
						FROM EMP
                        WHERE EMPNO IN (SELECT MGR
										FROM EMP
                                        WHERE EMPNO IN (SELECT MGR
														FROM EMP
                                                        WHERE JOB = 'SALESMAN')));
	-- BY JOIN
		SELECT DISTINCT E3.ENAME,D3.DNAME,D3.LOC
        FROM EMP E1,EMP E2,EMP E3,DEPT D3
        WHERE E3.DEPTNO = D3.DEPTNO AND E1.MGR = E2.EMPNO AND E2.MGR = E3.EMPNO AND E1.JOB = 'SALESMAN';

-- 10.⁠ ⁠LIST EMPLOYEES WHO ARE WORKING IN RESEARCH DEPT AND THEY ARE MANAGER.
	SELECT ENAME
    FROM EMP
    WHERE DEPTNO IN (SELECT DEPTNO
						FROM DEPT
                        WHERE DNAME = 'RESEARCH') AND JOB = 'MANAGER';
	-- BY JOIN
	SELECT ENAME
    FROM EMP,DEPT
    WHERE EMP.DEPTNO = DEPT.DEPTNO AND DNAME = 'RESEARCH' AND JOB = 'MANAGER';
    
-- 11.⁠ ⁠DISPLAY THE NUMBER OF EMPLOYEES WHO ARE GETTING SALARY LESS THAN THE BLAKE'S MANAGER.
	SELECT COUNT(*)
    FROM EMP
    WHERE SAL < (SELECT SAL
					FROM EMP
                    WHERE EMPNO IN ( SELECT MGR
										FROM EMP
                                        WHERE ENAME = 'BLAKE'));
	SELECT COUNT(*)
    FROM EMP E1,EMP E2,EMP E3
    WHERE  E2.MGR = E3.EMPNO AND E1.SAL < E3.SAL AND E2.ENAME = 'BLAKE';
    
-- 12.⁠ ⁠LIST THE EMPLOYEE DEPTNAME AND LOCATION OF ALL THE EMPLOYEES WHO ARE ANALYST, REPORTING TO BLAKE.
	SELECT DNAME,LOC 
    FROM DEPT
    WHERE DEPTNO IN (SELECT DEPTNO
						FROM EMP
                        WHERE JOB = 'ANALYST' AND MGR IN (SELECT EMPNO
															FROM EMP
                                                            WHERE ENAME = 'BLAKE'));
	SELECT D1.DNAME,D1.LOC
    FROM EMP E1,EMP E2,DEPT D1
    WHERE E1.DEPTNO = D1.DEPTNO AND E1.MGR = E2.EMPNO AND E2.ENAME = 'BLAKE' AND E1.JOB = 'ANALYST' ;
-- 13.⁠ ⁠DISPLAY THE EMPLOYEE NAMES, HIREDATE, COMM OF FORD'S MANAGER
	SELECT ENAME,HIREDATE,COMM
    FROM EMP
    WHERE EMPNO IN (SELECT MGR
					FROM EMP 
                    WHERE ENAME = 'FORD');
                    
	SELECT E1.ENAME,E1.HIREDATE,E1.COMM
    FROM EMP E1,EMP E2
    WHERE E1.EMPNO = E2.MGR AND E2.ENAME = 'FORD';

-- 14.⁠ ⁠DISPLAY ENAME, DNAME OF ALL THE EMPLOYEES WHOSE SALARY LESS THAN AVG SAL OF DEPT 30
	SELECT ENAME,DNAME
    FROM EMP , DEPT
    WHERE EMP.DEPTNO = DEPT.DEPTNO AND SAL < (SELECT AVG(SAL)
												FROM EMP
                                                WHERE DEPTNO = 30);
	

-- 15.⁠ ⁠DISPLAY ENAME DNAME AND LOC OF ALL THE EMPLOYEES WHO ARE WORKING FOR JONES
	SELECT ENAME,DNAME,LOC 
    FROM EMP,DEPT
    WHERE EMP.DEPTNO = DEPT.DEPTNO AND MGR IN (SELECT EMPNO
													FROM EMP
                                                    WHERE ENAME = 'JONES');

-- 16.⁠ ⁠DISPLAY ENAME DNAME OF ALL THE EMPLOYEES WHOSE NAME STARTS WITH S
	SELECT ENAME,DNAME
    FROM EMP, DEPT
    WHERE EMP.DEPTNO = DEPT.DEPTNO AND ENAME LIKE 'S%';

-- 17.⁠ ⁠LIST THE DNAME WHO ARE NOT HAVING ANY EMPLOYEE IN IT
	SELECT DNAME
    FROM DEPT
    WHERE DEPTNO NOT IN (SELECT DEPTNO
						 FROM EMP);

-- 18.DISPLAY EMPLOYEE WHO ARE GETTING SAME COMMISSION
	SELECT ENAME
    FROM EMP
    WHERE COMM IN (SELECT COMM
					FROM EMP
                    GROUP BY COMM
                    HAVING COUNT(*)>1);

-- 19.DISPLAY ALL THE DEPT NAMES IRRESPECTIVE OF ANY EMPLOYEE WORKING IN IT OR NOT. IF AN EMPLOYEE IS WORKING DISPLAY HIS NAME. 
	SELECT DEPT.DNAME,EMP.ENAME
    FROM EMP RIGHT JOIN DEPT
    ON EMP.DEPTNO = DEPT.DEPTNO;

-- 20.WRITE A QUERY TO DISPLAY EMPLOYEE NAME, JOB, DNAME, LOCATION OF ALL EMPLOYEES WHO ARE WORKING AS ACTUAL MANAGERS AND WORKS AT CHICAGO.
	SELECT EMP.ENAME,EMP.JOB,DEPT.DNAME,DEPT.LOC
    FROM EMP,DEPT
    WHERE EMP.DEPTNO = DEPT.DEPTNO AND JOB = 'MANAGER' AND LOC = 'CHICAGO';

-- 21.⁠ ⁠LIST THE DEPARTMENT NAMES IN WHICH THE EMPLOYEES ARE HIRED BETWEEN 1ST OF JAN 1981 AND 31ST DEC 1982 WITH SALARY MORE THAN 1800.
	SELECT DNAME
    FROM DEPT
    WHERE DEPTNO IN (SELECT DEPTNO
						FROM EMP
                        WHERE HIREDATE BETWEEN '1981-01-02' AND '1982-12-30' AND SAL > 1800);
                        
	SELECT DNAME
    FROM EMP,DEPT
    WHERE EMP.DEPTNO=DEPT.DEPTNO AND HIREDATE BETWEEN '1981-01-02' AND '1982-12-30' AND SAL > 1800;

-- 22.⁠ ⁠DISPLAY 2ND LEAST SALARY FROM EMPLOYEE TABLE.
	SELECT MIN(SAL)
    FROM EMP
    WHERE SAL > (SELECT MIN(SAL)
					FROM EMP);

-- 23.⁠ ⁠LIST THE EMPLOYEES WHOSE ANNUAL SALARY IS GREATER THAN 1500 AND WHO ARE JOINED BEFORE 1982 ONLY.
	SELECT *
    FROM EMP
    WHERE SAL*12 > 1500 AND HIREDATE < '1982-01-01';

-- 24.⁠ ⁠DISPLAY DNAME, LOC, DEPTNO OF EMPLOYEES WHO HAS SAME REPORTING MANAGER
SELECT DISTINCT DNAME, LOC, EMP.DEPTNO
FROM EMP,DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO AND MGR IN (
									SELECT MGR
									FROM EMP
									WHERE MGR IS NOT NULL
									GROUP BY MGR
									HAVING COUNT(*) > 1);
    
    
	SELECT DNAME,LOC,DEPTNO
    FROM DEPT
    WHERE DEPTNO IN (SELECT DEPTNO FROM EMP
									WHERE MGR IN (SELECT MGR
									               FROM EMP
                                                   WHERE MGR IS NOT NULL
													GROUP BY MGR
													HAVING COUNT(*) > 1));

-- 25.DISPLAY EMPLOYEE NAME ALONG WITH THEIR MANAGER NAME.
	SELECT E1.ENAME,E2.ENAME AS MANAGER
    FROM EMP E1,EMP E2
    WHERE E1.MGR = E2.EMPNO;
    

-- 26.DISPLAY EMPLOYEE NAME AND HIS DEPT NAME FOR THE EMPLOYEES WHOSE NAME STARTS WITH 'S'.
	SELECT ENAME,DNAME
    FROM EMP,DEPT
    WHERE EMP.DEPTNO = DEPT.DEPTNO AND ENAME LIKE 'S%';

-- 27.DISPLAY EMPLOYEES WHO ARE GETTING SAME SALARY.
	SELECT ENAME
    FROM EMP
    WHERE SAL IN (SELECT SAL
					FROM EMP
					GROUP BY SAL
					HAVING COUNT(*) > 1);
                    
-- 28.WAQTD DEPTNO AND NUMBER OF EMP WORKING ONLY IF THERE ARE 2 EMP WORKING IN EACH DEPT AS CLERK
	
SELECT DEPTNO, COUNT(*)
FROM EMP
WHERE DEPTNO IN (
    SELECT DEPTNO
    FROM EMP
    WHERE JOB = 'CLERK'
    GROUP BY DEPTNO
    HAVING COUNT(*) >= 2
)
GROUP BY DEPTNO;

-- SELECT EMP.SUM(SAL)
-- FROM EMP,DEPT
-- WHERE EMP.DEPTNO = DEPT.DEPTNO AND EMP.DEPTNO = 20;  --- THIS IS WRONG 

-- SELECT SUM(EMP.SAL)
-- FROM EMP,DEPT
-- WHERE EMP.DEPTNO = DEPT.DEPTNO AND EMP.DEPTNO = 20; -- THIS IS RIGHT      
                        
                        